Improving README
kool-dev/docker-php pull request #8
Opened 2020-10-05 22:10 UTC by wesleyhf

## README

- moving Environment Variables section to table
- adding COMPOSER_MEMORY_LIMIT on documentation (https://github.com/kool-dev/docker-php/commit/bb4fcc396216fb1587598068c3ad3b0fd1ace1b0)

2020-10-06 02:40 UTC, fabriciojs requested changes

2020-10-06 02:40 UTC, fabriciojs commented on README.md
> +Variable | Description | Default Value
can we change the order to help readability? making it `Variable | Default Value | Description`

2020-10-06 13:44 UTC, dbpolito commented on README.md
please add another section for NGINX variables...

2020-10-06 13:44 UTC, dbpolito commented on README.md
or a way to make it clear that these are for all images and nginx has a few more

2020-10-06 19:23 UTC, dbpolito commented
@wesleyhf 

We just introduced a few more env variables on nginx images: https://github.com/kool-dev/docker-php/pull/9

2020-10-07 22:50 UTC, dbpolito approved these changes

2020-10-07 22:51 UTC, merged